### ISSUE TITLE
Build issue: Sporth - paulstretch.c

### ISSUE THREAD

**Issue by rpherman** [PaulBatchelor/Sporth#16]
Paul,

I successfully built the dev branch of Soundpipe, installed and tested it with test.wav output.

When I try to make Sport, it bombs on paulstretch.c as follows:

`cc -O3 -fPIC -I/usr/local/include -Wall -DBUILD_LADSPA -Iugens/ladspa/ -I ugens/ling/ -g -c -Ih -I. ugens/paulstretch.c -o ugens/paulstretch.o
ugens/paulstretch.c: In function ‘sporth_paulstretch’:
ugens/paulstretch.c:12:5: error: unknown type name ‘sp_paulstretch’
     sp_paulstretch *paulstretch;
     ^
ugens/paulstretch.c:21:13: warning: implicit declaration of function ‘sp_paulstretch_create’ [-Wimplicit-function-declaration]
             sp_paulstretch_create(&paulstretch);
             ^
`
I am not enough of a build/make guy to understand the issue. I went to line 12:5 and I don't see the issue in the naming or the C code. Any ideas?

I really am looking forward to playing with Sporth again! Thanks.

Rob

**Comment by PaulBatchelor** [comment]
It looks like it's not recognizing the new module sp_paulstretch in soundpipe. Try git-pulling again on the dev branch of soundpipe?

**Comment by rpherman** [comment]
I originally did this: git clone -b dev https://github.com/PaulBatchelor/Soundpipe.git

And since tblrec.c is not in Master, but is in Dev, and I see it in my local git, doesn't that mean I did pull and build the Dev branch?

git branch -r shows I have Dev locally too.

`:~/Soundpipe$ git branch -r
  origin/HEAD -> origin/master
  origin/dev
  origin/master
  origin/wpkorg35
`

I'll go ahead and do it again, since it doesn't take too long anyway, and get back to you. Thanks!

**Comment by rpherman** [comment]
Thanks, Paul!

It all works. I must have messed something up with my Gitfu. Strange, because git branch said 'dev' and tblrec.lua was in there, and it is not in the master file list, only dev? Time to brush up on Git.

I just wiped the directory and did the following. I'll close this now, thanks:

` git clone https://github.com/PaulBatchelor/Soundpipe.git
 cd  Soundpipe
 git branch
 *master
 git checkout -b dev origin/dev
 git branch
*dev
`
