### ISSUE TITLE
faust2sporth not linking

### ISSUE THREAD

**Issue by martinjaroszewicz** [PaulBatchelor/Sporth#19]
Paul,
I think the script does not make the compiler link the .cpp and the .so files. 
I get a .so file instead of the the .sp
I also had to change the paths of the faust headers in sporth.cpp

**Comment by PaulBatchelor** [comment]
Faust2Sporth has only been tested on a few Linux machines, so it isn't surprise me that you'd be running into some compiler and path related issues.

Faust2Sporth is supposed to generate a .so file. This is a shared object file, that Sporth can load up as a plugin. See this blog post for more info:
http://paulbatchelor.github.io/blog/posts/2016-06-09-faust2sporth.html

**Comment by martinjaroszewicz** [comment]
Very interesting. Thank you.

**Comment by PaulBatchelor** [comment]
@martinjaroszewicz could you paste here what you changed the faust headers to, and what platform you are using?

**Comment by martinjaroszewicz** [comment]
In sporth.cpp
```
#include "faust/gui/UI.h"
#include "faust/audio/dsp.h"
#include "faust/gui/meta.h"
```
to where they are because I don't know compiler directives
```
faust/architecture/faust/gui/UI.h
faust/architecture/faust/dsp/dsp.h
faust/architecture/faust/gui/meta.h
```
Ubuntu 16.04

**Comment by PaulBatchelor** [comment]
You're on Linux? Huh. It should have worked without a hitch. 

What version of Faust are you running? 

I just compiled Faust using the master branch, and the files are in the right places. Running "Faust --version" gives me:

> FAUST, DSP to C++ compiler, Version 0.9.81
> Copyright (C) 2002-2015, GRAME - Centre National de Creation Musicale. All rights reserved.

**Comment by martinjaroszewicz** [comment]
Same here. This is strange but not an issue for me.

> faust --version
FAUST, DSP to C++ compiler, Version 0.9.81
Copyright (C) 2002-2015, GRAME - Centre National de Creation Musicale. All rights reserved.

**Comment by PaulBatchelor** [comment]
Can you see if /usr/local/include/faust exists? 

This is what I get when I run "ls /usr/local/include/faust"

> au  audio  dsp  gui  libfaust.h  midi  misc.h  osc  sound-file.h  vst

If this folder does exist, it must mean that Ubuntu does not have /usr/local/include in the header search path. I have pushed a changed to the faust2sporth script that explicitly looks for headers in this path so you shouldn't run into this issue anymore.

If that folder does not exist or looks significantly different, it means that something is strange with the Faust installation on Ubuntu, which is an issue I can't really fix on my end.

**Comment by martinjaroszewicz** [comment]
Yes:
``
au  audio  dsp  gui  midi  misc.h  osc  sound-file.h  vst
``

**Comment by PaulBatchelor** [comment]
Okay. I made some tweaks to faust2sporth and pushed it to master. It should be fixed now.

**Comment by martinjaroszewicz** [comment]
``
dist.cpp:41:29: fatal error: faust/audio/dsp.h: No such file or directory
compilation terminated.
``
I guess the problem is that the dsp.h is in dsp/dsp.h instead of audio/dsp.h

**Comment by PaulBatchelor** [comment]
Yup. I looks like I didn't do a full clean of my faust2 files. Once I do that, I get that error. I have pushed that fix. See if things work now.

**Comment by martinjaroszewicz** [comment]
Perfect!
