### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by postspectacular** [PaulBatchelor/Sporth#2]
Hi Paul, have just cloned & built Soundpipe and tried installing Sporth, but `make` fails with:

```
ugens/pluck.c:47:27: error: no member named 'pick' in 'sp_pluck'
            pluck->pluck->pick = sporth_stack_pop_float(stack);
            ~~~~~~~~~~~~  ^
ugens/pluck.c:70:27: error: no member named 'pick' in 'sp_pluck'
            pluck->pluck->pick = sporth_stack_pop_float(stack);
            ~~~~~~~~~~~~  ^
```

I'm guessing `pluck->pluck->pick` has become `pluck->pluck->pickup`, so I changed that, but then there're more errors which I've got no idea how to fix:

```
ugens/tin.c:8:5: error: unknown type name 'sp_tin'; did you mean 'sp_in'?
    sp_tin *tin;
    ^~~~~~
    sp_in
/usr/local/include/soundpipe.h:744:3: note: 'sp_in' declared here
} sp_in;
  ^
ugens/tin.c:17:13: warning: implicit declaration of function 'sp_tin_create' is invalid in C99 [-Wimplicit-function-declaration]
            sp_tin_create(&tin);
            ^
ugens/tin.c:18:55: error: use of undeclared identifier 'sp_tin'; did you mean 'sp_in'?
            plumber_add_module(pd, SPORTH_TIN, sizeof(sp_tin), tin);
                                                      ^
/usr/local/include/soundpipe.h:744:3: note: 'sp_in' declared here
} sp_in;
  ^
ugens/tin.c:33:13: warning: implicit declaration of function 'sp_tin_init' is invalid in C99 [-Wimplicit-function-declaration]
            sp_tin_init(pd->sp, tin);
            ^
ugens/tin.c:44:13: warning: implicit declaration of function 'sp_tin_compute' is invalid in C99 [-Wimplicit-function-declaration]
            sp_tin_compute(pd->sp, tin, &trig, &out);
            ^
ugens/tin.c:49:13: warning: implicit declaration of function 'sp_tin_destroy' is invalid in C99 [-Wimplicit-function-declaration]
            sp_tin_destroy(&tin);
```

Am really keen to try this out so any pointers are highly appreciated! :)

**Comment by PaulBatchelor** [comment]
Hey Karsten,

You'll need to use the 'dev' branch of Soundpipe. This isn't written anywhere, so I've made a note of it in the README. Let me know if that fixes things. If you have issues with building Soundpipe dev, feel free to use this ticket to report it.

**Comment by postspectacular** [comment]
:+1: - Thanks & all working! Now on to reverse engineerring/learning by example... :) V. impressed so far though! Do you plan or think either Soundpipe or Sporth could be used for live coding too?

**Comment by PaulBatchelor** [comment]
Thanks!

Soundpipe by itself couldn't/shouldn't be used for live coding, but it can certainly be used as an audio engine for one!

In theory, yes, Sporth could be used for live coding. I have even been working on an experimental live coding environment called Sporthlive, which is in the util folder. I wouldn't try it out yet though, unless you don't mind getting your hands dirty, as nothing is documented yet. I also have plans on getting Sporth inside of ChucK, which I think may be able to do.
