### ISSUE TITLE
compile error with  ugens/dcblock.c

### ISSUE THREAD

**Issue by poetaster** [PaulBatchelor/Sporth#2]
```
ugens/dcblock.c: In function ‘sporth_dcblock’:
ugens/dcblock.c:9:5: error: unknown type name ‘sp_dcblocker’; did you mean ‘sp_dcblock’?
    9 |     sp_dcblocker *data;
      |     ^~~~~~~~~~~~
```
I'm not sure if you're maintaining anymore. I noticed you've archived soundpipe ...?  Thanks!

**Comment by PaulBatchelor** [comment]
Just pushed some changes. Can you try seeing if things work now?

**Comment by poetaster** [comment]
Thanks! That's a clean make && install.

**Comment by poetaster** [comment]
I'll close this as the last commit fixes.
