### ISSUE TITLE
Slice ugen compilation error

### ISSUE THREAD

**Issue by martinjaroszewicz** [PaulBatchelor/Sporth#20]
Is this a new ugen? Could it be that the slice (sp_slice struct) doesn't exist in Soundpipe ?
```
ugens/slice.c:13:5: error: unknown type name ‘sp_slice’
     sp_slice *slice;
     ^
ugens/slice.c:22:13: warning: implicit declaration of function ‘sp_slice_create’ [-Wimplicit-function-declaration]
             sp_slice_create(&slice);
             ^
ugens/slice.c:59:13: warning: implicit declaration of function ‘sp_slice_init’ [-Wimplicit-function-declaration]
             sp_slice_init(pd->sp, slice, vals, buf);
             ^
ugens/slice.c:66:18: error: request for member ‘id’ in something not a structure or union
             slice->id = id;
                  ^
ugens/slice.c:67:13: warning: implicit declaration of function ‘sp_slice_compute’ [-Wimplicit-function-declaration]
             sp_slice_compute(pd->sp, slice, &trig, &out);
             ^
ugens/slice.c:72:13: warning: implicit declaration of function ‘sp_slice_destroy’ [-Wimplicit-function-declaration]
             sp_slice_destroy(&slice);
             ^
Makefile:51: recipe for target 'ugens/slice.o' failed
make: *** [ugens/slice.o] Error 1
```

**Comment by PaulBatchelor** [comment]
slice is a new module that i had on another branch in soundpipe. Compile soundpipe now and it should be fine?

**Comment by martinjaroszewicz** [comment]
Excellent ! 
BTW. It says in the description: in memory slice based sampler. Does it plays a buffer at a specific location for n samples? (perhaps for granular synthesis)

**Comment by PaulBatchelor** [comment]
Slice is built for beat slicing (hence, the name). It plays a buffer at specific slice mark, and then will play all the way up to the next slice mark. While it is sample accurate, it probably wouldn't work for granular synthesis, as there's no windowing or overlap. For granular synthesis, I would look things like fof and fog.
