### ISSUE TITLE
clock ugen error

### ISSUE THREAD

**Issue by peterdouglas** [PaulBatchelor/Sporth#21]
Hi Paul,

I am getting a compile error for sporth around the ugen/clock.c.

I noticed in a previous issue it was because you are currently working on a different branch of Soundpipe that is not dev. 

Is that the case here, or am I missing something?

I have installed Soundpipe from the dev branch and am on OSX.

During the make of sporth, I am getting errors related to unidentified identifiers sp_clock and clock. 

Thanks for your help. 

Peter

**Comment by PaulBatchelor** [comment]
Hey Peter!

Terribly sorry for the breakage. I believe I have fixed it. Clock was a new module I was working on over thanksgiving. It looks like I forgot to merge that branch and push the changes to Soundpipe. If you do a pull on Soundpipe dev and Sporth master, things should work now.

If things go well, could you report back to me here so I can close this issue?

**Comment by peterdouglas** [comment]
Hey Paul!

No worries. Thanks for the awesome work you do man ...

After pulling from dev again, I tried to run make on the dev branch of Soundpipe, and now seem to be getting a similar error.

cc -Wall -Ilib/inih/ -Ilib/faust -Ilib/kissfft/ -Dkiss_fft_scalar=float -Ilib/spa/ -DUSE_SPA -fPIC -g -DSP_VERSION=1.4.5 -O3 -DSPFLOAT=float -std=c99 -I./h -Ih -I/usr/local/include -fPIC -c -static modules/clock.c -o modules/clock.o
modules/clock.c:12:21: error: unknown type name 'sp_clock'
int sp_clock_create(sp_clock **p)
                    ^
modules/clock.c:14:24: error: use of undeclared identifier 'sp_clock'
    *p = malloc(sizeof(sp_clock));
                       ^
modules/clock.c:18:22: error: unknown type name 'sp_clock'
int sp_clock_destroy(sp_clock **p)
                     ^
modules/clock.c:24:32: error: unknown type name 'sp_clock'
int sp_clock_init(sp_data *sp, sp_clock *p)
                               ^
modules/clock.c:32:35: error: unknown type name 'sp_clock'
int sp_clock_compute(sp_data *sp, sp_clock *p, SPFLOAT *in, SPFLOAT *out)
                                  ^
5 errors generated.
make: *** [modules/clock.o] Error 1

**Comment by PaulBatchelor** [comment]
Did you run make clean first? The header file may need to regenerate.

Also do a full clean for Sporth when you recompile Sporth as well.

**Comment by peterdouglas** [comment]
Oops! That fixed it. They both successfully make and make install.

Thanks Paul!
