### ISSUE TITLE
Sporth Installed But No Sound

### ISSUE THREAD

**Issue by benschmaus** [PaulBatchelor/Sporth#23]
Hi, Paul.

I installed Sporth this morning and everything (including dependencies) appears to have installed ok but Sporth doesn't make any audio when I run the examples.  It also doesn't produce any errors.  Just looks like a noop.  Would appreciate any pointers if you have any ideas about how to fix.

I'm running OS X v10.12.3.

Here's how I installed:

1) Installed libsndfile via https://github.com/erikd/libsndfile
2) Cloned Soundpipe, checked out **dev** branch and installed.
3) Cloned Sporth and installed.

Everything installed without ostensible error.

Under `/usr/local/lib` I've got:

```
08:49 $ ls -l /usr/local/lib/libs
libsndfile.1.dylib  libsndfile.dylib    libsoundpipe.a
libsndfile.a        libsndfile.la       libsporth.a
```

And Sporth is installed under `/usr/local/bin`.

While running make for Sporth I saw a number or warnings in make output like:

```
In file included from ugens/polysporth/scheme-private.h:6:
ugens/polysporth/scheme.h:115:23: warning: redefinition of typedef 'scheme' is a C11 feature
      [-Wtypedef-redefinition]
typedef struct scheme scheme;
                      ^
h/plumber.h:139:23: note: previous definition is here
typedef struct scheme scheme;
```

Another is:

```
cc -O3 -fPIC -I/usr/local/include -Wall -ansi -g  -I ugens/cdb/ -I ugens/cdb/jsmn -I ugens/cdb/jsmn/ -DUSE_DL -DSTANDALONE=0 -Iugens/polysporth -g -c -Ih -I. plumber.c -o plumber.o
plumber.c:664:13: warning: implicit declaration of function 'usleep'
      [-Wimplicit-function-declaration]
            usleep(100);
            ^
1 warning generated.
```

Not sure if those matter or not.  Let me know what you think.

**Comment by benschmaus** [comment]
Perhaps this is user error on my part and not quite understanding how Sporth works.  I do get audio in the dialtone.wav example, but was expecting `echo "440 0.5 sine" | sporth` to produce sound, which I guess isn't how it works.

**Comment by PaulBatchelor** [comment]
Sporth doesn't support real-time audio for OSX by itself. It only produces audio files. 

There are several tools that can compile and play sporth in real-time, which include Chuck, PD, and AudioKit. You can also use the API and build a real-time implementation yourself using something like portaudio or rtaudio.

**Comment by benschmaus** [comment]
Thanks, Paul.  That makes sense.  After taking another pass through the doc at http://paulbatchelor.github.io/proj/sporth.html and running the examples it started making sense to me.  Appreciate the response and thanks for the pointers to portaudio and rtaudio.
