### ISSUE TITLE
Trailing spaces in ugen_reference.txt

### ISSUE THREAD

**Issue by rokf** [PaulBatchelor/Sporth#27]
While parsing the `ugen_reference.txt` file I noticed that it contains trailing spaces after some of the names.

**Comment by PaulBatchelor** [comment]
Thanks for bringing that to my attention. I think I removed them all. I used "/\s\+$" in Vim to find them. I have pushed these changes to the "dev" branch of Sporth. Can you verify that they are gone?

**Comment by rokf** [comment]
Yup, its fine now. Thank you :+1:
