### ISSUE TITLE
compilation fails without trailing linefeed

### ISSUE THREAD

**Issue by ritschwumm** [PaulBatchelor/Sporth#28]
a file containing
```
48 mtof
0.8 blsaw
```
without a trailing linefeed to a strange compilation error
```
Could not find function called 'blsa'.
blsa returned an error.
Uh-oh! Sporth created 1 error(s).
```
note the `blsa` - it seems the last character is cut off.

**Comment by PaulBatchelor** [comment]
What platform are you using? This is a strange bug I've seen on only the Mac platform for some reason.

**Comment by ritschwumm** [comment]
i'm on ubuntu

**Comment by PaulBatchelor** [comment]
Really? I have yet to be able to reproduce it on any of my Linux systems yet.

A few questions:

1. How are you running Sporth? 

2. How are you writing Sporth code?

**Comment by ritschwumm** [comment]
i've use a simple script
```
#!/bin/bash

sporth -r 44100 -b raw "$@" |
aplay -f FLOAT_LE -c 1 -r 44100
```
and called it with
```./sporth.sh test.sp```
where test.sp contained
```
00000000  34 38 20 6d 74 6f 66 0a  30 2e 38 20 62 6c 73 61  |48 mtof.0.8 blsa|
00000010  77 0a 38 30 30 30 20 38  20 31 30 30 20 6a 69 74  |w.8000 8 100 jit|
00000020  74 65 72 0a 30 2e 36 20  6d 6f 6f 67 6c 61 64 64  |ter.0.6 moogladd|
00000030  65 72 0a 72 6f 75 6e 64  0a                       |er.round.|
```
and right now (i rebooted in the meantime) the issue seems to have disappeared. weird - i could reproduce it every time before, and i had seen it in the past, too.

**Comment by PaulBatchelor** [comment]
I was able to reproduce the bug on OSX by writing the patch in TextEdit, rather than my usual text editor VIM. It turns out that TextEdit doesn't save a newline character "0xa" at the end of the last line. On vim, this character gets inserted at the end. 

What text editor are you using on Linux?

**Comment by ritschwumm** [comment]
oh, sorry - you are right, the problem occurs exactly when there is no 0x0a at the end. i made the file with jEdit (but other text editors would allow this, too).

**Comment by PaulBatchelor** [comment]
I'll see what I can do to fix this. This bug either exists in the parser code or in the custom getline implementation. Neither of those bits are fun to look at and debug, which is why I've avoided this bug for so long.

**Comment by PaulBatchelor** [comment]
I believe the bug has been fixed on the "dev" branch. @ritschwumm would you be able to confirm?

**Comment by ritschwumm** [comment]
at least the code change looks goot at first glance - put handwritten parsers are hard. i'll check later today when i have more time.

**Comment by ritschwumm** [comment]
thanks, works on the dev branch :)
