### ISSUE TITLE
Chorth

### ISSUE THREAD

**Issue by ziqbal** [PaulBatchelor/Sporth#33]
I'm trying to get Sporth in ChucK working but I'm stuck at:

[test.ck]:line(2): undefined type 'Sporth'...
[test.ck]:line(2): ... in declaration ...

I am using chuck version 1.4.0.0 and the latest Sporth/Chorch source all on linux.

**Comment by PaulBatchelor** [comment]
@ziqbal  Ah. It looks like I was manually copying chuck header files, and now they are too stale. I have updated those files, and some portions of Chorth as well. Things compile and run now on my OSX device, but I have yet to test it on Linux. Can you check and see if things work?

**Comment by ziqbal** [comment]
@PaulBatchelor Update works! Thank you for the fast response and fix.
