### ISSUE TITLE
csplit problem in WSL

### ISSUE THREAD

**Issue by jdfrank** [PaulBatchelor/Sporth#37]
hey, i'm running Ubuntu under windows. i got soudpipe made and installed. i got sporth made, but when i try to install my makings, i get a weird error from csplit. i'm messing around for a work around but have had no luck so far, and others might have a similar error so i'm posting here. 
![image](https://user-images.githubusercontent.com/1284405/49976408-c042dd80-ff0f-11e8-8f2b-4519932b1596.png)

**Comment by jdfrank** [comment]
Okay, some how all of my EOL characters got swapped to Windows style. I didn't open these files. i don't know if it was Github's desktop client or what. But hey, heads up on this issue for the WSL users. Now on to Sporthing!

**Comment by PaulBatchelor** [comment]
Did you end up getting things working okay? IIRC, there's a configuration for how to handle line feeds on Windows. I think you need to set it up so that it's alway uses the Unix LF instead of the Windows CRLF?

Happy Sporthing!
