### ISSUE TITLE
segfault in plumbing_compute at plumber.c:63

### ISSUE THREAD

**Issue by diamond-lizard** [PaulBatchelor/Sporth#38]
When I run the [simple.sp polysporth example](http://paulbatchelor.github.io/proj/polysporth.html) I get a segfault.  The backtrace is below:

```
gdb /usr/local/apps/sporth/bin/sporth
GNU gdb (Gentoo 8.1 p1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/apps/sporth/bin/sporth...done.
(gdb) run simple.sp
Starting program: /usr/local/apps/sporth/bin/sporth simple.sp
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
polysporth: not enough/wrong arguments
ps returned an error.
Uh-oh! Sporth created 2 error(s).

Program received signal SIGSEGV, Segmentation fault.
0x0000555555590fd6 in plumbing_compute (plumb=0x5555557f6b68, pipes=0x0, mode=3) at plumber.c:63
63          plumber_pipe *pipe = pipes->root.next;
(gdb) bt
#0  0x0000555555590fd6 in plumbing_compute (plumb=0x5555557f6b68, pipes=0x0, mode=3) at plumber.c:63
#1  0x00005555555911ee in plumber_compute (plumb=0x5555557f6b68, mode=3) at plumber.c:113
#2  0x0000555555591511 in plumber_clean (plumb=0x5555557f6b68) at plumber.c:206
#3  0x000055555555e2ec in ps_clean (ps=0x5555557f57d0) at ugens/polysporth/ps.c:131
#4  0x00005555555854ce in sporth_ps (stack=0x7fffffff5f40, ud=0x7fffffff3710) at ugens/polysporth.c:68
#5  0x0000555555591152 in plumbing_compute (plumb=0x7fffffff3710, pipes=0x7fffffff6260, mode=3) at plumber.c:96
#6  0x00005555555911ee in plumber_compute (plumb=0x7fffffff3710, mode=3) at plumber.c:113
#7  0x0000555555591511 in plumber_clean (plumb=0x7fffffff3710) at plumber.c:206
#8  0x0000555555594b7a in sporth_run (pd=0x7fffffff3710, argc=1, argv=0x7fffffffc460, ud=0x7fffffff3710, process=0x555555559cca <process>) at plumber.c:676
#9  0x0000555555559e1b in main (argc=2, argv=0x7fffffffc458) at sporth.c:36
```

This is on Gentoo amd64 Linux, on sporth compiled with jack.

**Comment by PaulBatchelor** [comment]
Oh man, Polysporth. It's been a while.

That example is out of date, as *are* all the examples there. Sorry about that. The examples you should be following can all be found [here](https://github.com/PaulBatchelor/Sporth/tree/master/ugens/polysporth/examples)

The main issue is the polysporth ugen: the arguments it takes in are different.

Have a look at [this example](https://github.com/PaulBatchelor/Sporth/blob/master/ugens/polysporth/examples/00_sine.sp) with the corresponding [scheme code](https://github.com/PaulBatchelor/Sporth/blob/master/ugens/polysporth/examples/00_sine.scm). Can you let me know if they work still?

Friendly warning: polysporth is an abandoned project of mine, and IMO not a pleasant experience compared to the other parts of this codebase. I personally have no plans to develop it any further, but if anyone else wants to have a go maintaining it, I say go for it! I think I left it in a reasonably okay state. I mostly lost interest in the idea, which is unfortunate considering how much time I put into it.

**Comment by PaulBatchelor** [comment]
To get the simple example working, use the following code for the sporth patch (simple.sp)

```
 4 _out "simple.scm" ps
 0 4 _out ftsum
```

The scheme code can be used normally:

```
 (define sine0 "60 mtof 0.2 sine")
 (define sine1 "64 mtof 0.2 sine")
 (define sine2 "67 mtof 0.2 sine")
 (ps-eval 0 sine0)
 (ps-eval 1 sine1)
 (ps-eval 2 sine2)
 (ps-turnon 0 -1)
 (ps-turnon 1 -1)
 (ps-turnon 2 -1)
```

I should probably update that page so it links to the github examples to avoid further confusion.

**Comment by PaulBatchelor** [comment]
Okay the website has been updated. Turns out the other examples on that page were already linking to the github page to begin with, so there was less to do than I expected.
