### ISSUE TITLE
Timing issue on metro/dmetro

### ISSUE THREAD

**Issue by takayukihamano** [PaulBatchelor/Sporth#39]
I love Sporth and I found a timing issue on metro/dmetro.
As shown in the attached image, both of metro and dmetro causes a time lag. In the image, I expected the impulses to be exactly at 10 seconds in both cases because the cookbook says “everything in Sporth is sample accurate.” The time lag seems to happen on every count. Maybe it’s a problem in Soundpipe.

I am planning to use it to make stimuli sounds for psychological experiments, so I appreciate if it’s more accurate.
![sporth_timing_issue](https://user-images.githubusercontent.com/5620909/51795566-db9c4a80-2228-11e9-8aad-f060ce6996cb.png)

**Comment by PaulBatchelor** [comment]
An issue has been added to the Soundpipe repo to update the documentation for dmetro. Closing the issue here now.
