### ISSUE TITLE
Creating user-defined functions dynamically?

### ISSUE THREAD

**Issue by mil** [PaulBatchelor/Sporth#41]
In Sporth, what's the best practice for creating a 'function' with arguments that can be subbed in dynamically at runtime?

E.g. what I'm trying to achieve is basically:
```forth
# Defining a function named fadein
1 tog (arg-substitution) 99 1 999 adsr *
_fadein functiondefine

# And then using the function with 20 as the arg-substitution
2000 1 sine 20 fadein
```

Is this sort of feature already achievable in Sporth somehow? The closest I've come so far is using p-registers but that's way more verbose than I'd like. Also I see the `f` ugen although it looks like that requires hard-coding the function's body.

**Comment by PaulBatchelor** [comment]
This kind of functionality is not available in Sporth. Sorry about that.
